on: [push]

jobs:
  test_notification:
    runs-on: ubuntu-latest
    name: Test WxPusher action
    steps:
      - uses: actions/checkout@v2
      - name: WxPusher Action
        uses: lxzxl/wxpusher-action@1.0
        id: wxpusher
        with:
          appToken: "${{ secrets.WP_APP_TOKEN }}"
          content: "成功"
      # Use the output from the `hello` step
      - name: Get the output response
        run: echo "Response - ${{ steps.wxpusher.outputs.response }}"
