on: [push]

jobs:
  test_notification:
    runs-on: ubuntu-latest
    name: Test WxPusher action
    steps:
      - uses: actions/checkout@v2
      - name: WxPusher Action
        uses: lxzxl/wxpusher-action@v1
        id: wxpusher
        with:
          appToken: "${{ secrets.WP_APP_TOKEN }}"
          summary: "${{ github.repository }}\n${{ github.ref }} 发布"
          topicIds: "955"
      # Use the output from the `hello` step
      - name: Get the output response
        run: echo "Response - ${{ steps.wxpusher.outputs.response }}"
